### ISSUE TITLE
Parsing EHLO responses should be more lax wrt. syntax errors.

### ISSUE THREAD

**Issue by rustonaut** [dac-gmbh/new-tokio-smtp#7]
If we can't understand the response we still can try to send mails!

Through I guess it also should log an warning, containing the not parsable line.

**Comment by RalfJung** [comment]
> Through I guess it also should log an warning, containing the not parsable line.

I guess the problem here is how to do the logging in a way that doesn't disturb the application using the library...

**Comment by rustonaut** [comment]
Yes, through using the log facility should be fine as most implementations allow you to filter logging by crate/module/path.

It's also the only way to do so API compatible.

A newer version with a braking change (v0.9) will likely return something like `Result<(T, Vec<Warnings>), Error>` or similar. I'm not yet quite sure about the design.

Then you can have a helper method to log or error on warnings and do something like
`smtp_stuff().and_then(log_non_fatal_error)?`, `smtp_stuff().and_then(error_on_non_fatal_errors)` or
`smtp_stuff().and_then(ignore_non_fatal_errors)?`.  Or something similar.

**Comment by rustonaut** [comment]
Ok, turns out that the idea with and_then will not work well with the current design, we might come back to this after switching to async/await.

So the new plan is:
- [ ] make it configurable if some non-fatal errors will cause a error or will be skipped (skipped is the default)
- [ ] make a feature flag to add the log facade (currently mainly for  "skipped" non-fatal errors).
      Not that this is about just making the log crate an optional dependency.

**Comment by rustonaut** [comment]
Resolved on  >=v0.9.0
